# Generated by Django 3.2.5 on 2021-08-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='phone_num',
            new_name='phone',
        ),
    ]
